### ISSUE TITLE
Is multiprocessing a good idea anyway?

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/chitin#28]
I'm not even sure if we want a multiprocessed shell. Sure, it can run jobs in parallel and is trivial to script, and also needs no configuration. But does anyone want this? Is it because I just don't want to hammer at GNU Parallel? I don't know.

**Comment by SamStudio8** [comment]
Fundamentally I think splitting the shell from the execution is a nice idea. I think this could pave the way forward for a daemon that can also act as a gateway to prevent running multiple jobs that will clobber eachother and provide integrity warnings. Potentially this daemon could act as a central point for multiple chitin users?

In the short term, I like that when I run a big samtools or GATK command, it's in the background and my shell lives on. We need to improve the feedback and provide a live view of what's going on, but it's pretty neat that we always have a shell that can take and queue input.

**Comment by SamStudio8** [comment]
I guess also, this puts us in an ideal position to decide how and when stuff gets executed.
Here is an opportunity to interface with the local system, or a remote host (over ssh), or through a job submission facility like SGE, LSF, or a hole deep in the ground.

**Comment by crazyhottommy** [comment]
I use GNU parallel extensively. I do not know how exactly you are implementing Chitin, but I want to let you know there are user cases :)

Tommy

**Comment by SamStudio8** [comment]
Thanks! My concern is whether I'd be reinventing the wheel, so to speak. I
think ultimately this way gives us the power to decide the mode of
execution.
Users could always just call GNU parallel themselves, I suppose...!

**Comment by SamStudio8** [comment]
idk, we've done it now so I guess we need to d-d-d-d-deal
